repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0 
    hooks:
      - id: black
        args: [--line-length=145]
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
